In [ ]:
import numpy as np

In [ ]:
sales=np.array([[1200,1500,1700],[1000,1100,1300]])

In [ ]:
sales[1]

array([1000, 1100, 1300])

In [ ]:
sales[1][2]

np.int64(1300)

In [ ]:
np.sum(sales)

np.int64(7800)

In [ ]:
np.mean(sales)

np.float64(1300.0)

In [ ]:
np.mean(sales,axis=1)

array([1466.66666667, 1133.33333333])

In [ ]:
np.mean(sales,axis=0)

array([1100., 1300., 1500.])

In [ ]:
data=np.arange(12)

In [ ]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
data2=np.reshape(data,(4,3))

In [ ]:
data2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
sales=np.array([1000,0,1200,0,1500])
sales


array([1000,    0, 1200,    0, 1500])

#to remove duplicates

In [ ]:
 np.mean(sales)

np.float64(740.0)

In [ ]:
filtered_sales=sales[sales>0]
filtered_sales

array([1000, 1200, 1500])

In [ ]:
np.mean(filtered_sales)

np.float64(1233.3333333333333)

generating dummy data
generating random numbers


In [ ]:
np.random.randint(100,1000,10)

array([613, 351, 731, 111, 880, 622, 604, 676, 776, 787])

**Pandas**

In [ ]:
import pandas as pd


In [ ]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.name
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.name="calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

**Indexing**

In [ ]:
s[2:4]

2    30
3    40
Name: calories, dtype: int64

In [ ]:
s.iloc[4]

np.int64(50)

In [ ]:
s.iloc[[1,4,3]]

1    20
4    50
3    40
Name: calories, dtype: int64

Changing the index values

In [ ]:
index=["apple","banana","grapes","orange","strawberry"]

In [ ]:
s.index=index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

label based indexing


In [ ]:
s.loc["apple":"strawberry"]

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

creating Serires from dictionary

In [ ]:
fruit_protien={
    "Avacado":2.0,
    "Guava":2.6,
    "BlackBerries":2.0,
    "Oranges":0.9,
    "Banana":1.1,
    "Apples":0.3,
    "Kiwi":1.1,
    "promogranate":1.7,
    "Mango":0.8,
    "cherries":1.0,
}

In [ ]:
s2=pd.Series(fruit_protien,name="protien")
s2

Avacado         2.0
Guava           2.6
BlackBerries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
promogranate    1.7
Mango           0.8
cherries        1.0
Name: protien, dtype: float64

Conditional Selections


In [ ]:
s2>1

Avacado          True
Guava            True
BlackBerries     True
Oranges         False
Banana           True
Apples          False
Kiwi             True
promogranate     True
Mango           False
cherries        False
Name: protien, dtype: bool

In [ ]:
s2[s2>1]

Avacado         2.0
Guava           2.6
BlackBerries    2.0
Banana          1.1
Kiwi            1.1
promogranate    1.7
Name: protien, dtype: float64

Logical Operation


In [ ]:
(s2>0.5) & (s2<1)

Avacado         False
Guava           False
BlackBerries    False
Oranges          True
Banana          False
Apples          False
Kiwi            False
promogranate    False
Mango            True
cherries        False
Name: protien, dtype: bool

In [ ]:
s2[(s2>0.5)&(s2<=2)]

Avacado         2.0
BlackBerries    2.0
Oranges         0.9
Banana          1.1
Kiwi            1.1
promogranate    1.7
Mango           0.8
cherries        1.0
Name: protien, dtype: float64

OR operation

In [ ]:
s2[(s2>0.5)|(s2<=2)]

Avacado         2.0
Guava           2.6
BlackBerries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
promogranate    1.7
Mango           0.8
cherries        1.0
Name: protien, dtype: float64

Not operation


In [ ]:
s2[~(s2<1)]

Avacado         2.0
Guava           2.6
BlackBerries    2.0
Banana          1.1
Kiwi            1.1
promogranate    1.7
cherries        1.0
Name: protien, dtype: float64

Changing values in Series

In [ ]:
s2["Mango"]=3.8
s2

Avacado         2.0
Guava           2.6
BlackBerries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
promogranate    1.7
Mango           3.8
cherries        1.0
Name: protien, dtype: float64

In [ ]:
r=pd.Series['a',np.nan,1,np.nan,2]
r.notnull().sum()

TypeError: type 'Series' is not subscriptable

Data Frame


In [ ]:
data={
    "Name":["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age":[25,30,35,np.nan,29,25],
    "Department":["HR","IT","Finance","HR","IT","Finance"],
    "Salary":[50000,60000,55000,np.nan,62000,50000]
}


In [ ]:
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'HR', 'IT', 'Finance'],
 'Salary': [50000, 60000, 55000, nan, 62000, 50000]}

In [ ]:
df=pd.DataFrame(data)
df

Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  29.0         IT  62000.0
5    Alice  25.0    Finance  50000.0

Head function

In [ ]:
df.head(2)

Name   Age Department   Salary
0  Alice  25.0         HR  50000.0
1    Bob  30.0         IT  60000.0

Tail Function

In [ ]:
df.tail(2)

Name   Age Department   Salary
4    Eve  29.0         IT  62000.0
5  Alice  25.0    Finance  50000.0

loc and iloc

In [ ]:
df.iloc[2:4]

Name   Age Department   Salary
2  Charlie  35.0    Finance  55000.0
3    David   NaN         HR      NaN

In [ ]:
df.iloc[::-1]

Name   Age Department   Salary
5    Alice  25.0    Finance  50000.0
4      Eve  29.0         IT  62000.0
3    David   NaN         HR      NaN
2  Charlie  35.0    Finance  55000.0
1      Bob  30.0         IT  60000.0
0    Alice  25.0         HR  50000.0

In [ ]:
df.loc[2:3]

Name   Age Department   Salary
2  Charlie  35.0    Finance  55000.0
3    David   NaN         HR      NaN

In [ ]:
df.loc[2:3,["Age","Department"]]

Age Department
2  35.0    Finance
3   NaN         HR

In [ ]:
df.iloc[2:4,1:3]

Age Department
2  35.0    Finance
3   NaN         HR

Accessing individula column

In [ ]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df[["Age","Department"]]

Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         HR
4  29.0         IT
5  25.0    Finance

Dropping columns



In [ ]:
df.drop("Age",axis=1)

Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  55000.0
3    David         HR      NaN
4      Eve         IT  62000.0
5    Alice    Finance  50000.0

In [ ]:
df

Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  29.0         IT  62000.0
5    Alice  25.0    Finance  50000.0

inplace should be true for deleting the values from the main table

In [ ]:
df.drop("Age",axis=1)

Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  55000.0
3    David         HR      NaN
4      Eve         IT  62000.0
5    Alice    Finance  50000.0

In [ ]:
df

Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  29.0         IT  62000.0
5    Alice  25.0    Finance  50000.0

In [ ]:
data={
    "Name":["Alice","Bob","Charlie","David","Eve","Alice"],
    "Age":[25,30,35,np.nan,29,25],
    "Department":["HR","IT","Finance","HR","IT","Finance"],
    "Salary":[50000,60000,55000,np.nan,62000,50000]
}

In [ ]:
df

Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  29.0         IT  62000.0
5    Alice  25.0    Finance  50000.0

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        6 non-null      object 
 1   Age         5 non-null      float64
 2   Department  6 non-null      object 
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes


In [ ]:
df.describe()

Age       Salary
count   5.000000      5.00000
mean   28.800000  55400.00000
std     4.147288   5549.77477
min    25.000000  50000.00000
25%    25.000000  50000.00000
50%    29.000000  55000.00000
75%    30.000000  60000.00000
max    35.000000  62000.00000

BroadCasting

In [ ]:
#increasing the salary by 5000
df["Salary"]=df["Salary"]+5000
df

Name   Age Department   Salary
0    Alice  25.0         HR  65000.0
1      Bob  30.0         IT  75000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         HR      NaN
4      Eve  29.0         IT  77000.0
5    Alice  25.0    Finance  65000.0

In [ ]:
df["Salary"]

0    65000.0
1    75000.0
2    70000.0
3        NaN
4    77000.0
5    65000.0
Name: Salary, dtype: float64

Renaming Columns

In [ ]:
df.rename(columns={"Department":"Dept"},inplace=True)

In [ ]:
df

Name   Age     Dept   Salary
0    Alice  25.0       HR  65000.0
1      Bob  30.0       IT  75000.0
2  Charlie  35.0  Finance  70000.0
3    David   NaN       HR      NaN
4      Eve  29.0       IT  77000.0
5    Alice  25.0  Finance  65000.0

To get unique values from a Column

In [ ]:
df["Salary"].unique()

array([65000., 75000., 70000.,    nan, 77000.])

Value counts in each department

In [ ]:
df["Dept"].value_counts()

Dept
HR         2
IT         2
Finance    2
Name: count, dtype: int64

In [ ]:
df["Promoted Salary"]=df["Salary"]*10

In [ ]:
df

Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  65000.0         650000.0
1      Bob  30.0       IT  75000.0         750000.0
2  Charlie  35.0  Finance  70000.0         700000.0
3    David   NaN       HR      NaN              NaN
4      Eve  29.0       IT  77000.0         770000.0
5    Alice  25.0  Finance  65000.0         650000.0

Data Cleaning


In [ ]:
#checking for null values
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [ ]:
#removing null value
df.dropna(how="any")

Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  65000.0         650000.0
1      Bob  30.0       IT  75000.0         750000.0
2  Charlie  35.0  Finance  70000.0         700000.0
4      Eve  29.0       IT  77000.0         770000.0
5    Alice  25.0  Finance  65000.0         650000.0

In [ ]:
df.dropna(how="all")

Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  65000.0         650000.0
1      Bob  30.0       IT  75000.0         750000.0
2  Charlie  35.0  Finance  70000.0         700000.0
3    David   NaN       HR      NaN              NaN
4      Eve  29.0       IT  77000.0         770000.0
5    Alice  25.0  Finance  65000.0         650000.0

In [ ]:
#filling null values
df.fillna(0)

Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  65000.0         650000.0
1      Bob  30.0       IT  75000.0         750000.0
2  Charlie  35.0  Finance  70000.0         700000.0
3    David   0.0       HR      0.0              0.0
4      Eve  29.0       IT  77000.0         770000.0
5    Alice  25.0  Finance  65000.0         650000.0

In [ ]:
#filling with mean
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
#filling with median
df["Salary"].fillna(df["Salary"].median())

0    65000.0
1    75000.0
2    70000.0
3    70000.0
4    77000.0
5    65000.0
Name: Salary, dtype: float64

Forward Fill and Backward Fill

In [ ]:
#forward fill
df["Age"].fillna(method='ffill')

/tmp/ipython-input-3955773429.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method='ffill')


0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
#backward fill
df["Age"].fillna(method='bfill')

/tmp/ipython-input-1101808371.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method='bfill')


0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

Changing the values in a column

In [ ]:
df["Name"].replace("Charlie","Rose")

0    Alice
1      Bob
2     Rose
3    David
4      Eve
5    Alice
Name: Name, dtype: object

In [ ]:
df

Name   Age     Dept   Salary  Promoted Salary
0    Alice  25.0       HR  65000.0         650000.0
1      Bob  30.0       IT  75000.0         750000.0
2  Charlie  35.0  Finance  70000.0         700000.0
3    David  28.8       HR      NaN              NaN
4      Eve  29.0       IT  77000.0         770000.0
5    Alice  25.0  Finance  65000.0         650000.0

In [ ]:
#changing the data in the main table

df["Name"]=df["Name"].replace("Charlie","Rose")

In [ ]:
df

Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  65000.0         650000.0
1    Bob  30.0       IT  75000.0         750000.0
2   Rose  35.0  Finance  70000.0         700000.0
3  David  28.8       HR      NaN              NaN
4    Eve  29.0       IT  77000.0         770000.0
5  Alice  25.0  Finance  65000.0         650000.0

Handling Duplicate values

In [ ]:
df_dup=df[df.duplicated()]
df_dup

Empty DataFrame
Columns: [Name, Age, Dept, Salary, Promoted Salary]
Index: []

In [ ]:
df_duplicate=df[df.duplicated(keep='first')]
df_duplicate

Empty DataFrame
Columns: [Name, Age, Dept, Salary, Promoted Salary]
Index: []

In [ ]:
df_duplicate

Empty DataFrame
Columns: [Name, Age, Dept, Salary, Promoted Salary]
Index: []

Dropping duplicates

In [ ]:
df=df.drop_duplicates(subset="Name",keep='last')
df

Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  65000.0         650000.0
1    Bob  30.0       IT  75000.0         750000.0
2   Rose  35.0  Finance  70000.0         700000.0
3  David  28.8       HR      NaN              NaN
4    Eve  29.0       IT  77000.0         770000.0

Handling invalid values

In [ ]:
#lambda
df["Promoted Salary"]=df["Promoted Salary"].apply(lambda x:x/10 if x>65000 else x)

In [ ]:
df

Name   Age     Dept   Salary  Promoted Salary
0  Alice  25.0       HR  65000.0          65000.0
1    Bob  30.0       IT  75000.0          75000.0
2   Rose  35.0  Finance  70000.0          70000.0
3  David  28.8       HR      NaN              NaN
4    Eve  29.0       IT  77000.0          77000.0

In [ ]:
name="alice_fernandes"
df[["first_name","last_name"]]=df["name"].str.split("_")

apply and lambda

In [ ]:
#multiplying age
def multiplying_age(x):
  return x*2
df["Age"]=df["Age"].apply(multiplying_age)

In [ ]:
df

Name   Age     Dept   Salary  Promoted Salary
0  Alice  50.0       HR  65000.0          65000.0
1    Bob  60.0       IT  75000.0          75000.0
2   Rose  70.0  Finance  70000.0          70000.0
3  David  57.6       HR      NaN              NaN
4    Eve  58.0       IT  77000.0          77000.0

In [ ]:
#using lambda
df["Age"]=df["Age"].apply(lambda x:x/2)

In [ ]:
df


Name   Age     Dept   Salary  Promoted Salary
0  Alice  50.0       HR  65000.0          65000.0
1    Bob  60.0       IT  75000.0          75000.0
2   Rose  70.0  Finance  70000.0          70000.0
3  David  57.6       HR      NaN              NaN
4    Eve  58.0       IT  77000.0          77000.0

In [ ]:
import pandas as pd

Joins and Merges

In [ ]:
department_info={
    "Department":["HR","IT","Finance"],
    "Location":["New York","San Fransisco","Chicago"],
    "Manager":["Alice","Bob","Charlie"]
}
df2=pd.DataFrame(department_info)
df2


Department       Location  Manager
0         HR       New York    Alice
1         IT  San Fransisco      Bob
2    Finance        Chicago  Charlie

In [ ]:
df

Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  55000.0
3    David   NaN         HR      NaN
4      Eve  29.0         IT  62000.0
5    Alice  25.0    Finance  50000.0

In [ ]:
#concat
pd.concat([df,df2])

Name   Age Department   Salary       Location  Manager
0    Alice  25.0         HR  50000.0            NaN      NaN
1      Bob  30.0         IT  60000.0            NaN      NaN
2  Charlie  35.0    Finance  55000.0            NaN      NaN
3    David   NaN         HR      NaN            NaN      NaN
4      Eve  29.0         IT  62000.0            NaN      NaN
5    Alice  25.0    Finance  50000.0            NaN      NaN
0      NaN   NaN         HR      NaN       New York    Alice
1      NaN   NaN         IT      NaN  San Fransisco      Bob
2      NaN   NaN    Finance      NaN        Chicago  Charlie

In [ ]:
#concat column wise
pd.concat([df,df2],axis=1)

Name   Age Department   Salary Department       Location  Manager
0    Alice  25.0         HR  50000.0         HR       New York    Alice
1      Bob  30.0         IT  60000.0         IT  San Fransisco      Bob
2  Charlie  35.0    Finance  55000.0    Finance        Chicago  Charlie
3    David   NaN         HR      NaN        NaN            NaN      NaN
4      Eve  29.0         IT  62000.0        NaN            NaN      NaN
5    Alice  25.0    Finance  50000.0        NaN            NaN      NaN

In [ ]:
#merge
pd.merge(df,df2,on='Department')

Name   Age Department   Salary       Location  Manager
0    Alice  25.0         HR  50000.0       New York    Alice
1      Bob  30.0         IT  60000.0  San Fransisco      Bob
2  Charlie  35.0    Finance  55000.0        Chicago  Charlie
3    David   NaN         HR      NaN       New York    Alice
4      Eve  29.0         IT  62000.0  San Fransisco      Bob
5    Alice  25.0    Finance  50000.0        Chicago  Charlie

Importing File

In [ ]:
data=pd.read_csv(mnist_test.csv)

In [ ]:
#changing the data type to date and time
data['date']=pd.to_datetime(df['date'])